/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferaybook.courses.manager.model;

import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the CourseSubscription service. Represents a row in the &quot;lb_CourseSubscription&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferaybook.courses.manager.model.impl.CourseSubscriptionModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferaybook.courses.manager.model.impl.CourseSubscriptionImpl</code>.
 * </p>
 *
 * @author Vitaliy Koshelenko
 * @see CourseSubscription
 * @generated
 */
@ProviderType
public interface CourseSubscriptionModel extends BaseModel<CourseSubscription> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a course subscription model instance should use the {@link CourseSubscription} interface instead.
	 */

	/**
	 * Returns the primary key of this course subscription.
	 *
	 * @return the primary key of this course subscription
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this course subscription.
	 *
	 * @param primaryKey the primary key of this course subscription
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the course subscription ID of this course subscription.
	 *
	 * @return the course subscription ID of this course subscription
	 */
	public long getCourseSubscriptionId();

	/**
	 * Sets the course subscription ID of this course subscription.
	 *
	 * @param courseSubscriptionId the course subscription ID of this course subscription
	 */
	public void setCourseSubscriptionId(long courseSubscriptionId);

	/**
	 * Returns the course ID of this course subscription.
	 *
	 * @return the course ID of this course subscription
	 */
	public long getCourseId();

	/**
	 * Sets the course ID of this course subscription.
	 *
	 * @param courseId the course ID of this course subscription
	 */
	public void setCourseId(long courseId);

	/**
	 * Returns the user ID of this course subscription.
	 *
	 * @return the user ID of this course subscription
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this course subscription.
	 *
	 * @param userId the user ID of this course subscription
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this course subscription.
	 *
	 * @return the user uuid of this course subscription
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this course subscription.
	 *
	 * @param userUuid the user uuid of this course subscription
	 */
	public void setUserUuid(String userUuid);

	@Override
	public CourseSubscription cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}