/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferaybook.courses.manager.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Lecture service. Represents a row in the &quot;lb_Lecture&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferaybook.courses.manager.model.impl.LectureModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferaybook.courses.manager.model.impl.LectureImpl</code>.
 * </p>
 *
 * @author Vitaliy Koshelenko
 * @see Lecture
 * @generated
 */
@ProviderType
public interface LectureModel
	extends BaseModel<Lecture>, GroupedModel, ShardedModel, StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a lecture model instance should use the {@link Lecture} interface instead.
	 */

	/**
	 * Returns the primary key of this lecture.
	 *
	 * @return the primary key of this lecture
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this lecture.
	 *
	 * @param primaryKey the primary key of this lecture
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this lecture.
	 *
	 * @return the uuid of this lecture
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this lecture.
	 *
	 * @param uuid the uuid of this lecture
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the lecture ID of this lecture.
	 *
	 * @return the lecture ID of this lecture
	 */
	public long getLectureId();

	/**
	 * Sets the lecture ID of this lecture.
	 *
	 * @param lectureId the lecture ID of this lecture
	 */
	public void setLectureId(long lectureId);

	/**
	 * Returns the company ID of this lecture.
	 *
	 * @return the company ID of this lecture
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this lecture.
	 *
	 * @param companyId the company ID of this lecture
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this lecture.
	 *
	 * @return the group ID of this lecture
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this lecture.
	 *
	 * @param groupId the group ID of this lecture
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this lecture.
	 *
	 * @return the user ID of this lecture
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this lecture.
	 *
	 * @param userId the user ID of this lecture
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this lecture.
	 *
	 * @return the user uuid of this lecture
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this lecture.
	 *
	 * @param userUuid the user uuid of this lecture
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this lecture.
	 *
	 * @return the user name of this lecture
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this lecture.
	 *
	 * @param userName the user name of this lecture
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this lecture.
	 *
	 * @return the create date of this lecture
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this lecture.
	 *
	 * @param createDate the create date of this lecture
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this lecture.
	 *
	 * @return the modified date of this lecture
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this lecture.
	 *
	 * @param modifiedDate the modified date of this lecture
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the course ID of this lecture.
	 *
	 * @return the course ID of this lecture
	 */
	public long getCourseId();

	/**
	 * Sets the course ID of this lecture.
	 *
	 * @param courseId the course ID of this lecture
	 */
	public void setCourseId(long courseId);

	/**
	 * Returns the name of this lecture.
	 *
	 * @return the name of this lecture
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this lecture.
	 *
	 * @param name the name of this lecture
	 */
	public void setName(String name);

	/**
	 * Returns the description of this lecture.
	 *
	 * @return the description of this lecture
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this lecture.
	 *
	 * @param description the description of this lecture
	 */
	public void setDescription(String description);

	/**
	 * Returns the video link of this lecture.
	 *
	 * @return the video link of this lecture
	 */
	@AutoEscape
	public String getVideoLink();

	/**
	 * Sets the video link of this lecture.
	 *
	 * @param videoLink the video link of this lecture
	 */
	public void setVideoLink(String videoLink);

	/**
	 * Returns the url title of this lecture.
	 *
	 * @return the url title of this lecture
	 */
	@AutoEscape
	public String getUrlTitle();

	/**
	 * Sets the url title of this lecture.
	 *
	 * @param urlTitle the url title of this lecture
	 */
	public void setUrlTitle(String urlTitle);

	@Override
	public Lecture cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}